# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
 - task: PowerShell@2
   inputs:
     filePath: 'post-file-to-discord.ps1'

# - task: cURLUploader@2
#   inputs:
#     files: 'Enigmatica4-0.1.1.zip'
#     authType: 'UserAndPass'
#     url: 'https://discordapp.com/api/webhooks/$(WEBHOOK_ID)/$(WEBHOOK_TOKEN)'