# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'server'

steps:
# - task: PowerShell@2
#   inputs:
#     filePath: 'post-file-to-discord.ps1'

- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    method: 'POST'
    headers: |
      {
      "Content-Type":"multipart/form-data"
      }
    body: |
      {
      "content":"Enigmatica4-0.1.1.zip"
      }
    urlSuffix: 'https://discordapp.com/api/webhooks/$(WEBHOOK_ID)/$(WEBHOOK_TOKEN)'
    waitForCompletion: 'false'