# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: cURLUploader@2
  inputs:
    files: 'Enigmatica4-0.1.1.zip'
    URL: 'https://discordapp.com/api/webhooks/$(WEBHOOK_ID)/$(WEBHOOK_TOKEN)'