
["Basic Ender Gate"]
	#Range: min = 1, max = 16
	channels = "2"
	#Range: min = 0, max = 2147483647
	transfer = "4000"

["Hardened Ender Gate"]
	#Range: min = 1, max = 16
	channels = "4"
	#Range: min = 0, max = 2147483647
	transfer = "8000"

["Blazing Ender Gate"]
	#Range: min = 1, max = 16
	channels = "7"
	#Range: min = 0, max = 2147483647
	transfer = "16000"

["Niotic Ender Gate"]
	#Range: min = 1, max = 16
	channels = "11"
	#Range: min = 0, max = 2147483647
	transfer = "32000"

["Spirited Ender Gate"]
	#Range: min = 1, max = 16
	channels = "16"
	#Range: min = 0, max = 2147483647
	transfer = "64000"

