
#Range: min = 0, max = 2147483647
["Basic Enregy Cell"]
	transfer = "1000"
	capacity = "100000"

["Hardened Enregy Cell"]
	transfer = "2000"
	capacity = "200000"

["Blazing Enregy Cell"]
	transfer = "4000"
	capacity = "400000"

["Niotic Enregy Cell"]
	transfer = "8000"
	capacity = "800000"

["Spirited Enregy Cell"]
	transfer = "16000"
	capacity = "1600000"

