#
#List of fluids used in Magmatic Generator.
#fluid registry name = heat per 100 mb eg: ["minecraft:lava=10000", "examplemod:fluid=1000"]
#Min = 1, max = 2147483647
magmaticFluids = ["minecraft:lava=10000"]
#Enable this to allow other mods to add their fluids. [default:true]
magmaticFluidsAPI = true

#Range: min = 0, max = 2147483647
["Basic Magmatic Generator"]
	capacity = "75000"
	transfer = "120"
	perTick = "60"

["Hardened Magmatic Generator"]
	capacity = "150000"
	transfer = "240"
	perTick = "120"

["Blazing Magmatic Generator"]
	capacity = "300000"
	transfer = "480"
	perTick = "240"

["Niotic Magmatic Generator"]
	capacity = "600000"
	transfer = "960"
	perTick = "480"

["Spirited Magmatic Generator"]
	capacity = "1200000"
	transfer = "1920"
	perTick = "960"

