
[entity]

	#Entity Mob
	[entity.mob]
		#Allow AI tasks to be removed from entities at runtime. If this is disable no per mob or per mob type removes will run.
		allow_remove_calls = true

	[entity.entity]

		#Entity Mob
		[entity.entity.mob]
			#Remove the look at goal (player or attack target) AI task. This will cause AIs to not face targets or walking directions.
			remove_look_goal = false
			#Replaces the default look controller with a version featuring cached tan math improving performance. Only works on vanilla style mobs, if a mod overrides the look controller it will skip.
			replace_look_controller = true
			#Remove the look at random position AI task. This will cause AIs to feel a little lifeless as they do not animate head movement while idle.
			remove_look_random = false

		[entity.entity.entity]

			#Entity Fish
			[entity.entity.entity.fish]
				#Remove the fish's random swimming pathfinder. This will cause fish to stay in position more often.
				remove_swim = false
				#Remove the fish's panic pathfinder. This will cause fish to not run away.
				remove_panic = false
				#Remove the fish's AI task to avoid players.
				remove_avoid_player = false

