
#General settings
[general]

	#Powercell settings
	[general.powercell]
		#Maximum RF a single tier3 cell can hold
		#Range: 1 ~ 2000000000
		tier3MaxRF = 20000000
		#Maximum RF/tick per side for a tier1 cell
		#Range: 1 ~ 2000000000
		tier1MaxRFPerTick = 2000
		#Maximum RF/tick per side for a tier3 cell
		#Range: 1 ~ 2000000000
		tier3MaxRFPerTick = 8000
		#Maximum RF/tick per side for a tier2 cell
		#Range: 1 ~ 2000000000
		tier2MaxRFPerTick = 4000
		#Maximum RF a single tier1 cell can hold
		#Range: 1 ~ 2000000000
		tier1MaxRF = 500000
		#Maximum number of blocks in a single multiblock network
		#Range: 1 ~ 2000000000
		networkMax = 1000
		#Maximum RF a single tier2 cell can hold
		#Range: 1 ~ 2000000000
		tier2MaxRF = 4000000
		#How much extra RF/tick every cell gets per cell in the network. 0 means constant RF/t. 1 means linear with amount of cells
		#Range: 0.0 ~ 100.0
		rfPerTickScale = 0.5

	#Coal generator settings
	[general.coalgenerator]
		#RF per tick that the generator can send
		#Range: > 0
		generatorRFPerTick = 10000
		#Amount of ticks generated per coal
		#Range: > 0
		ticksPerCoal = 600
		#Maximum RF storage that the generator can hold
		#Range: > 0
		generatorMaxRF = 500000
		#RF per tick that the generator can charge items with
		#Range: > 0
		generatorChargePerTick = 1000
		#Whether the coal generator should exist
		enabled = true
		#Amount of RF generated per tick
		#Range: > 0
		generatePerTick = 40

