
[general]
	#Level of Feather Falling needed
	#Range: 1 ~ 3
	level = 1
	#When should farmland get trampled
	#Never: Never trampled farmland
	#Always: It Always get trampled
	#Default: Normal behavior
	#Feather Falling: Does not get trampled with you have feather falling boots
	type = "FEATHER_FALLING"

